feat: add `rudof`
w3c-cg/awesome-semantic-shapes pull request #13
Opened 2024-11-21 17:46 UTC by jeswr

[rudof](https://rudof-project.github.io/rudof/cli_usage/convert.html) was recently presented by @labra at ISWC!

2024-11-21 18:40 UTC, TallTed requested changes

2024-11-21 18:40 UTC, TallTed commented on README.md
> +- [rudof](rudof) [![Latest Version](https://img.shields.io/crates/v/rudof-cli.svg)](https://crates.io/crates/rudof-cli) [![PyPI](https://img.shields.io/pypi/v/pyrudof)](https://pypi.org/project/pyrud
```suggestion
- [rudof](rudof) [![Latest Version](https://img.shields.io/crates/v/rudof-cli.svg)](https://crates.io/crates/rudof-cli) [![PyPI](https://img.shields.io/pypi/v/pyrudof)](https://pypi.org/project/pyrudof/) [![rudof](https://github.com/rudof-project/rudof/actions/workflows/ci.yml/badge.svg)](https://github.com/rudof-project/rudof/actions/workflows/ci.yml) [![dependency status](https://deps.rs/repo/github/rudof-project/rudof/status.svg)](https://deps.rs/repo/github/rudof-project/rudof) is a library that implements [Shape Expressions](https://shex.io/), [SHACL](https://www.w3.org/TR/shacl/), [DCTAP](https://www.dublincore.org/specifications/dctap/), and other technologies in the [RDF](https://www.w3.org/RDF/) ecosystem. The library is implemented in [Rust](https://www.rust-lang.org/) and also provides Python bindings.
```

2024-11-21 18:40 UTC, TallTed commented on README.md
> +- [rudof](rudof) [![Latest Version](https://img.shields.io/crates/v/rudof-cli.svg)](https://crates.io/crates/rudof-cli) [![PyPI](https://img.shields.io/pypi/v/pyrudof)](https://pypi.org/project/pyrud
```suggestion
- [rudof](rudof) [![Latest Version](https://img.shields.io/crates/v/rudof-cli.svg)](https://crates.io/crates/rudof-cli) [![PyPI](https://img.shields.io/pypi/v/pyrudof)](https://pypi.org/project/pyrudof/) [![rudof](https://github.com/rudof-project/rudof/actions/workflows/ci.yml/badge.svg)](https://github.com/rudof-project/rudof/actions/workflows/ci.yml) [![dependency status](https://deps.rs/repo/github/rudof-project/rudof/status.svg)](https://deps.rs/repo/github/rudof-project/rudof) is a library that implements [Shape Expressions](https://shex.io/), [SHACL](https://www.w3.org/TR/shacl/), [DCTAP](https://www.dublincore.org/specifications/dctap/), and other technologies in the [RDF](https://www.w3.org/RDF/) ecosystem. The library is implemented in [Rust](https://www.rust-lang.org/) and also provides Python bindings.
```

2024-11-22 20:32 UTC, jeswr commented
Issues identified in https://github.com/w3c-cg/awesome-semantic-shapes/issues/15 should now be resolved. Please feel free to make any further changes directly.

2024-11-26 16:05 UTC, VladimirAlexiev commented
@jeswr do we have these from https://rudof-project.github.io/rudof/#related-projects ?
- [ShEx-s](https://www.weso.es/shex-s/), a Scala implementation of ShEx (This project started as a re-implementation of ShEx-s in Rust).
- [SHACL-s](https://www.weso.es/shacl-s/), a Scala implementation of SHACL.
- [ShEx.js](https://github.com/shexjs/shex.js), a Javascript implementation of ShEx.

2024-11-26 16:06 UTC, merged

2024-11-26 16:17 UTC, jeswr commented
> @jeswr do we have these from https://rudof-project.github.io/rudof/#related-projects ?
> - [ShEx-s](https://www.weso.es/shex-s/), a Scala implementation of ShEx (This project started as a re-implementation of ShEx-s in Rust).
> - [SHACL-s](https://www.weso.es/shacl-s/), a Scala implementation of SHACL.
> - [ShEx.js](https://github.com/shexjs/shex.js), a Javascript implementation of ShEx.

Ah no, it would be good if they were added - can I leave this to you to do?

2024-11-26 17:27 UTC, VladimirAlexiev commented
@jeswr added to https://github.com/w3c-cg/awesome-semantic-shapes/issues/18