Update SPARNA
w3c-cg/awesome-semantic-shapes pull request #30
Opened 2024-12-10 10:15 UTC by Marie-Sparna

adding pointers to SHACL Play

2024-12-12 12:56 UTC, VladimirAlexiev requested changes

2024-12-12 12:56 UTC, VladimirAlexiev commented on README.md
> +  - [RDF validator](https://www.itb.ec.europa.eu/shacl/any/upload) - The EU Interoperability Test Bed (ITB) playground based on TQ API; validate any RDF with SHACL Shapes.
Your PR seems based on an older version of the README. There is duplication about ITB (lines 37, 38 and 40), please rebase it.

2024-12-12 12:56 UTC, VladimirAlexiev commented on README.md
> +  - [Sparna SHACL validator](https://shacl-play.sparna.fr/play/validate) - Free online suite of tools from Sparna to work with SHACL; based on TQ API.
Let's not have 2 bullets for SPARNA (lines 39 and 41) in the same section.

2024-12-16 11:43 UTC, Marie-Sparna commented
Hi Vladimir,

Thank you for your message, I removed both additional ITB lines, can you
tell me if everything ok now ?

Best,

*Marie Muller* -* SPARNA*
Web de *données* | Architecture de l'*information* | Accès aux
*connaissances*
blog : blog.sparna.fr, site : sparna.fr


Le jeu. 12 déc. 2024 à 13:56, Vladimir Alexiev ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/w3c-cg/awesome-semantic-shapes/pull/30#discussion_r1882012167>
> :
>
> > @@ -34,6 +34,9 @@ Software tools or libraries, sorted by programming language.
>  - [Apache Jena SHACL](https://github.com/apache/jena/tree/main/jena-shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.apache.jena/jena-shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.apache.jena/jena-shacl" align="top"> - Supports SHACL Core, SHACL-SPARQL; [docs](https://jena.apache.org/documentation/shacl/index.html); `Apache-2.0` license; `Java`.
>  - [RDF4J SHACL Engine](https://github.com/eclipse-rdf4j/rdf4j/tree/main/core/sail/shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.eclipse.rdf4j/rdf4j-shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.eclipse.rdf4j/rdf4j-shacl" align="top"> - Supports SHACL Core (without some property paths, see [5.0.3 improvements](https://github.com/Sveino/Inst4CIM-KG/issues/95#issuecomment-2437819932)), SHACL-SPARQL, incremental validation; [docs](https://rdf4j.org/documentation/programming/shacl/); `BSD-3-Clause` license; `Java`.
>  - [TopBraid SHACL API](https://github.com/TopQuadrant/shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.topbraid/shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.topbraid/shacl" align="top"> 💰 - Supports SHACL Core, SHACL-SPARQL, SHACL rules; based on Jena; `BSD-3-Clause` license; `Java`.
> +  - [RDF validator](https://www.itb.ec.europa.eu/shacl/any/upload) - The EU Interoperability Test Bed (ITB) playground based on TQ API; validate any RDF with SHACL Shapes.
>
> Your PR seems based on an older version of the README. There is
> duplication about ITB (lines 37, 38 and 40), please rebase it.
> ------------------------------
>
> In README.md
> <https://github.com/w3c-cg/awesome-semantic-shapes/pull/30#discussion_r1882013218>
> :
>
> > @@ -34,6 +34,9 @@ Software tools or libraries, sorted by programming language.
>  - [Apache Jena SHACL](https://github.com/apache/jena/tree/main/jena-shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.apache.jena/jena-shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.apache.jena/jena-shacl" align="top"> - Supports SHACL Core, SHACL-SPARQL; [docs](https://jena.apache.org/documentation/shacl/index.html); `Apache-2.0` license; `Java`.
>  - [RDF4J SHACL Engine](https://github.com/eclipse-rdf4j/rdf4j/tree/main/core/sail/shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.eclipse.rdf4j/rdf4j-shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.eclipse.rdf4j/rdf4j-shacl" align="top"> - Supports SHACL Core (without some property paths, see [5.0.3 improvements](https://github.com/Sveino/Inst4CIM-KG/issues/95#issuecomment-2437819932)), SHACL-SPARQL, incremental validation; [docs](https://rdf4j.org/documentation/programming/shacl/); `BSD-3-Clause` license; `Java`.
>  - [TopBraid SHACL API](https://github.com/TopQuadrant/shacl) <img alt="Maven Central Version" src="https://img.shields.io/maven-central/v/org.topbraid/shacl" align="top"> <img alt="Maven Central Last Update" src="https://img.shields.io/maven-central/last-update/org.topbraid/shacl" align="top"> 💰 - Supports SHACL Core, SHACL-SPARQL, SHACL rules; based on Jena; `BSD-3-Clause` license; `Java`.
> +  - [RDF validator](https://www.itb.ec.europa.eu/shacl/any/upload) - The EU Interoperability Test Bed (ITB) playground based on TQ API; validate any RDF with SHACL Shapes.
> +  - [SHACL shapes validator](https://www.itb.ec.europa.eu/shacl/shacl/upload) - The EU Interoperability Test Bed (ITB) playgrounds based on TQ API; validate SHACL Shapes itself.
> +  - [Sparna SHACL validator](https://shacl-play.sparna.fr/play/validate) - Free online suite of tools from Sparna to work with SHACL; based on TQ API.
>
> Let's not have 2 bullets for SPARNA (lines 39 and 41) in the same section.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c-cg/awesome-semantic-shapes/pull/30#pullrequestreview-2499423850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5E3ICC2RA7LDQMRYMXIMET2FGBYHAVCNFSM6AAAAABTKZPXOCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJZGQZDGOBVGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-17 09:56 UTC, merged

2024-12-17 09:56 UTC, VladimirAlexiev commented
@Marie-Sparna Thanks a lot! Merged